// Anonymous structural cases only. Never imported by application code.
export const time='2026-09-05T00:00:00.000Z';
export const authority={scopeId:'s0',rootPersonId:'p0',sourceIds:new Set(['s1'])};
export function graph(){return {schemaVersion:1,scopeId:'s0',graphVersion:'v1',rootPersonId:'p0',people:['p0','p1'].map(id=>({id,displayName:id,aliases:[],identityIds:[],affiliations:[],identityConfidence:1,updatedAt:time})),identities:[],organizations:[],observedLinks:[{id:'l0',fromPersonId:'p0',toPersonId:'p1',kind:'CONTACT_SAVED',evidenceIds:['e0'],confidence:1,observedAt:time}],relationships:[],searchEdges:[{id:'x0',relationshipId:null,fromPersonId:'p0',toPersonId:'p1',strength:0.5,confidence:1,recencyFactor:1,evidenceIds:['e0'],basis:'OBSERVED_CONNECTION_PRIOR',policyVersion:'prior-v1'}],evidence:[{id:'e0',sourceId:'s1',summary:'e0',observedAt:time,confidence:1,claimKind:'RELATIONSHIP'}],sources:[{id:'s1',provider:'MANUAL',label:'s1',origin:'USER_PROVIDED',importedAt:time}],coverage:{completeForAuthorizedSources:true,omittedNodeCount:0,warnings:[]}};}
export function path(){return {id:'path0',personIds:['p0','p1'],edgeIds:['x0'],target:{personId:'p1',relevance:1,evidenceIds:['e0'],reasons:[],criteria:[]},score:{value:0.5,relationshipQuality:0.5,identityQuality:1,targetRelevance:1,hopPenalty:1,edges:[{edgeId:'x0',strength:0.5,confidence:1,recencyFactor:1,value:0.5}],identities:[{personId:'p1',value:1}],policyVersion:'route-v1'},explanation:{summary:'e0',evidenceIds:['e0'],uncertainties:[],suggestedFirstContactId:'p1'}};}
export function result(){const p=path();const stats={expansions:1,elapsedMs:1,stop:'EXHAUSTED_WITHIN_HOP_LIMIT',optimalWithinHopLimit:true,traceTruncated:false,omittedTraceEvents:0};const env={schemaVersion:1,scopeId:'s0',graphVersion:'v1',searchId:'q0'};return {...env,goal:{id:'g0',text:'g0',organizationIds:[],roles:[],locations:[],industries:[],unsupportedConstraints:[]},targets:[p.target],paths:[p],events:[{...env,seq:0,type:'SEARCH_STARTED',rootPersonId:'p0'},{...env,seq:1,type:'EDGE_EXPLORED',edgeId:'x0',fromPersonId:'p0',toPersonId:'p1'},{...env,seq:2,type:'PATH_SELECTED',pathId:'path0'},{...env,seq:3,type:'SEARCH_COMPLETED',pathIds:['path0'],stats}],stats,warnings:[]};}
export function batch(){return {schemaVersion:1,batchId:'b0',sourceId:'s1',people:[{tempId:'t0',displayName:'t0',identities:[{platform:'m0',externalId:'a0'}],evidenceIds:['e1']}],relationships:[],observedLinks:[{fromRef:'p0',toRef:'t0',kind:'CONTACT_SAVED',evidenceIds:['e1']}],affiliations:[],evidence:[{id:'e1',sourceId:'s1',summary:'e1',observedAt:time,confidence:1,claimKind:'RELATIONSHIP'}],warnings:[]};}
export const batchAuthority={sourceId:'s1',batchId:'b0',existingPersonIds:new Set(['p0','p1']),existingEvidenceIds:new Set(['e0'])};
export const context={scopeId:'s0',ownerUserId:'u0',sourceId:'s1',batchId:'b0',sharingDecisionId:null,sourcePolicyVersion:'v1'};
export function envelope(){return {context:{...context},batch:batch(),records:[{id:'rec0',sourceId:'s1',ownerUserId:'u0',externalRecordId:'record0',retrievedAt:time,contentDigest:'0'.repeat(64),privatePayloadRef:'blob0'}],evidenceRecords:[{evidenceId:'e1',sourceRecordId:'rec0'}],facts:[{factKey:'fact0',sourceRecordId:'rec0',kind:'OBSERVED_LINK',candidateIndex:0,fromIdentity:{platform:'m0',externalId:'root0'},toIdentity:{platform:'m0',externalId:'a0'}}]};}
export const importAuthority={...batchAuthority,...context,existingIdentities:[{platform:'m0',externalId:'root0',personId:'p0'}]};
