import test from 'node:test';import assert from 'node:assert/strict';
import {validateNormalizedImport,validateIdentityLinkRequest,validateIdentityRevertRequest,validateGraphBuildEvent,ContractError} from '../dist/contracts/validation.js';
import {envelope,importAuthority,graph} from './fixtures.mjs';
test('private provenance validates, affiliation absence normalizes to unknown',()=>{const n=envelope();n.batch.affiliations=[{personRef:'t0',organizationName:'o0',evidenceIds:['e1']}];n.facts.push({factKey:'fact1',sourceRecordId:'rec0',kind:'AFFILIATION',candidateIndex:0,personIdentity:{platform:'m0',externalId:'a0'}});const parsed=validateNormalizedImport(n,importAuthority);assert.equal(parsed.batch.affiliations[0].current,null);assert.equal(n.batch.affiliations[0].current,undefined);});
for(const [name,mutate] of Object.entries({
 'owner mismatch':n=>{n.records[0].ownerUserId='u9';},'missing evidence provenance':n=>{n.evidenceRecords=[];},'foreign record':n=>{n.facts[0].sourceRecordId='rec9';},'missing fact':n=>{n.facts=[];},'wrong source identity endpoint':n=>{n.facts[0].fromIdentity.externalId='a9';},'bad candidate index':n=>{n.facts[0].candidateIndex=9;},'duplicate fact key':n=>{n.facts.push(n.facts[0]);},'raw payload field':n=>{n.records[0].raw='opaque';},'identity reassignment':n=>{n.batch.people[0].identities[0].externalId='root0';}
}))test(`normalization rejects ${name}`,()=>{const n=envelope();mutate(n);assert.throws(()=>validateNormalizedImport(n,importAuthority),ContractError);});
test('identity requests select explicit mappings and authorized reversals',()=>{const g=graph();g.identities=[{id:'i0',personId:'p0'}];const r={scopeId:'s0',expectedGraphVersion:'v1',identityId:'i0',expectedPersonId:'p0',nextPersonId:null,idempotencyKey:'k0'};validateIdentityLinkRequest(r,g);assert.throws(()=>validateIdentityLinkRequest({...r,expectedPersonId:'p1'},g),ContractError);assert.throws(()=>validateIdentityLinkRequest({...r,nextPersonId:'p9'},g),ContractError);const revert={scopeId:'s0',expectedGraphVersion:'v1',decisionId:'d0',idempotencyKey:'k1'};validateIdentityRevertRequest(revert,'s0','v1',new Set(['d0']));assert.throws(()=>validateIdentityRevertRequest(revert,'s0','v2',new Set(['d0'])),ContractError);});
test('source removal invalidates snapshot and requires removed source to be absent',()=>{const before=graph(),after=graph();after.graphVersion='v2';after.sources=[];after.evidence=[];after.searchEdges=[];after.observedLinks=[];const ctx={jobId:'j0',scopeId:'s0',afterSeq:0,before,after,candidateIds:new Set(),proposalIds:new Set()};const e={schemaVersion:1,jobId:'j0',scopeId:'s0',seq:1,type:'SNAPSHOT_INVALIDATED',baseGraphVersion:'v1',graphVersion:'v2',reason:'SOURCE_REMOVED',removedSourceIds:['s1']};validateGraphBuildEvent(e,ctx);assert.throws(()=>validateGraphBuildEvent(e,{...ctx,after:{...before,graphVersion:'v2'}}),ContractError);});
