import test from 'node:test';import assert from 'node:assert/strict';
import {BackendService,apiFailure} from '../dist/packages/server/service.js';
import {graph,result,batch,envelope} from './fixtures.mjs';
const scope={scopeId:'s0',ownerUserId:'u0',rootPersonId:'p0',sourceIds:new Set(['s1'])};
const request={scopeId:'s0',expectedGraphVersion:'v1',goalText:'g0'};
function ports(){return {auth:{resolveSession:async c=>c==='session0'?{userId:'u0'}:null},reads:{authorizePrivateScope:async (u,s)=>u==='u0'&&s==='s0'?scope:null,readSnapshot:async()=>graph()}};}
const rejectsCode=(promise,code)=>assert.rejects(promise,e=>e.code===code);
test('unauthenticated/other-scope requests never reach storage',async()=>{const p=ports();p.reads.readSnapshot=async()=>assert.fail('unauthorized read');const service=new BackendService(p);await rejectsCode(service.graph(null,'s0'),'UNAUTHENTICATED');await rejectsCode(service.graph('session0','s9'),'FORBIDDEN');});
test('repository cannot substitute another owner',async()=>{const p=ports();p.reads.authorizePrivateScope=async()=>({...scope,ownerUserId:'u9'});await rejectsCode(new BackendService(p).graph('session0','s0'),'FORBIDDEN');});
test('private authorized graph returns detached data and actual root',async()=>{const original=graph(),p=ports();p.reads.readSnapshot=async()=>original;const out=await new BackendService(p).graph('session0','s0');out.people[0].displayName='p9';assert.equal(original.people[0].displayName,'p0');});
test('missing storage and unconfigured engine fail explicitly',async()=>{const p=ports();await rejectsCode(new BackendService(p).search('session0',request),'SOURCE_UNAVAILABLE');p.reads.readSnapshot=async()=>null;await rejectsCode(new BackendService(p).graph('session0','s0'),'SOURCE_UNAVAILABLE');});
test('invalid persisted graph is internal failure, not caller input error',async()=>{const p=ports();p.reads.readSnapshot=async()=>({...graph(),scopeId:'s9'});await rejectsCode(new BackendService(p).graph('session0','s0'),'INTERNAL');});
test('stale search fails before invoking goal or graph engine',async()=>{const p=ports();p.goals={resolve:async()=>assert.fail('stale goal')};await rejectsCode(new BackendService(p).search('session0',{...request,expectedGraphVersion:'v0'}),'VERSION_CONFLICT');});
test('orchestration supplies session snapshot and clamps compute limits',async()=>{const p=ports();p.goals={resolve:async()=>({goal:result().goal,targets:result().targets})};p.engine={findBestPaths:(g,_goal,_targets,options)=>{assert.equal(g.rootPersonId,'p0');assert.deepEqual(options,{k:5,maxHops:6,maxExpansions:10000,maxFrontier:25000,maxTraceEvents:3000,deadlineMs:1000});return result();}};assert.equal((await new BackendService(p).search('session0',{...request,k:100,maxHops:100})).paths.length,1);});
test('optional start person is authorized against the original private snapshot and never changes its owner root',async()=>{
 const original=graph();original.people[1].identityIds=['i1'];original.identities=[{id:'i1',sourceId:'s1',platform:'public',externalId:'person1',personId:'p1',assignmentState:'CONFIRMED',evidenceIds:['e0'],updatedAt:original.people[1].updatedAt}];
 const p=ports();p.reads.readSnapshot=async()=>original;p.goals={resolve:async()=>({goal:result().goal,targets:[]})};p.engine={findBestPaths:g=>{assert.equal(g.rootPersonId,'p1');const out=result();out.targets=[];out.paths=[];out.stats={expansions:0,elapsedMs:1,stop:'NO_TARGETS',optimalWithinHopLimit:true,traceTruncated:false,omittedTraceEvents:0};out.events=[{...out.events[0],rootPersonId:'p1'},{...out.events.at(-1),seq:1,pathIds:[],stats:out.stats}];return out;}};
 const service=new BackendService(p);const found=await service.search('session0',{...request,startPersonId:'p1'});assert.equal(found.events[0].rootPersonId,'p1');assert.equal(original.rootPersonId,'p0');assert.equal(scope.rootPersonId,'p0');
 for(const input of [{...request,startPersonId:'p9'},{...request,startPersonId:'p0'}])await rejectsCode(service.search('session0',input),'FORBIDDEN');
 const denied=ports();denied.reads.readSnapshot=async()=>assert.fail('unauthorized selection read');await rejectsCode(new BackendService(denied).search(null,{...request,startPersonId:'p1'}),'UNAUTHENTICATED');
});
test('malicious engine cannot leak hidden events',async()=>{const p=ports();p.goals={resolve:async()=>({goal:result().goal,targets:result().targets})};p.engine={findBestPaths:()=>{const r=result();r.events[1].edgeId='hidden';return r;}};await rejectsCode(new BackendService(p).search('session0',request),'INTERNAL');});
test('private import stage validates before persistence; never confirms claims',async()=>{const p=ports();p.reads.readSnapshot=async()=>{const g=graph();g.people[0].identityIds=['i0'];g.identities=[{id:'i0',sourceId:'s1',platform:'m0',externalId:'root0',personId:'p0',assignmentState:'CONFIRMED',evidenceIds:['e0'],updatedAt:g.people[0].updatedAt}];return g;};let calls=0;p.imports={lookupRetry:async()=>null,stage:async input=>{calls++;assert.equal(input.actorUserId,'u0');assert.equal(input.envelope.batch.batchId,'b0');return {jobId:'j0',status:'PENDING_REVIEW',duplicate:false};}};const svc=new BackendService(p),context={scopeId:'s0',ownerUserId:'u0',sourceId:'s1',batchId:'b0',sharingDecisionId:null,sourcePolicyVersion:'v1'};assert.equal((await svc.stageImport('session0',context,'v1',envelope())).status,'PENDING_REVIEW');await rejectsCode(svc.stageImport('session0',{...context,ownerUserId:'u9'},'v1',envelope()),'FORBIDDEN');await rejectsCode(svc.stageImport('session0',{...context,sharingDecisionId:'d0'},'v1',envelope()),'FORBIDDEN');await rejectsCode(svc.stageImport('session0',context,'v0',envelope()),'VERSION_CONFLICT');assert.equal(calls,1);});
test('errors never echo internal/provider content',()=>{const out=apiFailure(new Error('sensitive payload'),'req0');assert.equal(out.status,500);assert.ok(!JSON.stringify(out).includes('sensitive'));});
