/**
 * Small Turso adapter for local tooling and portable deployments.
 *
 * The hosted Worker continues to use its D1 binding. This module is Node-only
 * and must never be imported by browser code: TURSO_AUTH_TOKEN is a secret.
 */
import { createClient } from '@libsql/client/web';

function databaseUrl(value) {
  const input = value.trim();
  if (!input.startsWith('libsql://') && !input.startsWith('https://')) {
    throw new Error('TURSO_DATABASE_URL must use libsql:// or https://.');
  }
  // @libsql/client/web converts libsql:// to HTTPS and appends the Hrana
  // pipeline path itself. Supplying /v2/pipeline here would append it twice.
  return input;
}

export function createTursoClient({ url = process.env.TURSO_DATABASE_URL, authToken = process.env.TURSO_AUTH_TOKEN } = {}) {
  if (!url?.trim()) throw new Error('TURSO_DATABASE_URL is required.');
  if (!authToken?.trim()) throw new Error('TURSO_AUTH_TOKEN is required.');
  if (/PASTE|YOUR_REAL|TOKEN_HERE/i.test(authToken)) {
    throw new Error('TURSO_AUTH_TOKEN is still a placeholder. Paste the token generated by Turso.');
  }
  return createClient({ url: databaseUrl(url), authToken: authToken.trim() });
}

// Adapt libSQL's execute/batch API to the D1-shaped API used by database.js.
// Keeping this boundary small lets the Worker switch databases by secret
// configuration without changing ingestion or traversal logic.
export function createTursoDatabase(config) {
  const client = createTursoClient(config);
  return {
    prepare(sql) {
      return {
        sql,
        args: [],
        bind(...args) { this.args = args; return this; },
        async all() { const result = await client.execute({ sql: this.sql, args: this.args }); return { results: result.rows }; },
        async first() { const result = await client.execute({ sql: this.sql, args: this.args }); return result.rows[0] ?? null; },
      };
    },
    async batch(statements) {
      const result = await client.batch(statements.map(statement => ({ sql: statement.sql, args: statement.args })), 'write');
      return result.map(entry => ({ results: entry.rows }));
    },
  };
}

export async function tursoHealth() {
  const client = createTursoClient();
  const result = await client.execute('SELECT 1 AS ok');
  return result.rows[0]?.ok === 1;
}
